/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PackedUserOperationStruct = {
  sender: AddressLike;
  nonce: BigNumberish;
  initCode: BytesLike;
  callData: BytesLike;
  accountGasLimits: BytesLike;
  preVerificationGas: BigNumberish;
  gasFees: BytesLike;
  paymasterAndData: BytesLike;
  signature: BytesLike;
};

export type PackedUserOperationStructOutput = [
  sender: string,
  nonce: bigint,
  initCode: string,
  callData: string,
  accountGasLimits: string,
  preVerificationGas: bigint,
  gasFees: string,
  paymasterAndData: string,
  signature: string
] & {
  sender: string;
  nonce: bigint;
  initCode: string;
  callData: string;
  accountGasLimits: string;
  preVerificationGas: bigint;
  gasFees: string;
  paymasterAndData: string;
  signature: string;
};

export interface AgentWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDeposit"
      | "changeOwner"
      | "checkBalance"
      | "entryPoint"
      | "execute"
      | "executeBatch"
      | "getDeposit"
      | "initialize"
      | "owner"
      | "sessionManager"
      | "setWhiteListedParty"
      | "setWhiteListedPartyBatch"
      | "validateUserOp"
      | "whiteListedParties"
      | "withdrawDepositTo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchExecutionPerformed"
      | "EntryPointDepositAdded"
      | "EntryPointWithdrawal"
      | "ExecutionPerformed"
      | "OwnerChanged"
      | "UserOperationValidated"
      | "WalletInitialized"
      | "WhiteListUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [AddressLike[], BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sessionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setWhiteListedParty",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhiteListedPartyBatch",
    values: [AddressLike[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "validateUserOp",
    values: [PackedUserOperationStruct, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whiteListedParties",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawDepositTo",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sessionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhiteListedParty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhiteListedPartyBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateUserOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whiteListedParties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDepositTo",
    data: BytesLike
  ): Result;
}

export namespace BatchExecutionPerformedEvent {
  export type InputTuple = [
    caller: AddressLike,
    callCount: BigNumberish,
    totalValue: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    callCount: bigint,
    totalValue: bigint
  ];
  export interface OutputObject {
    caller: string;
    callCount: bigint;
    totalValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntryPointDepositAddedEvent {
  export type InputTuple = [amount: BigNumberish, newBalance: BigNumberish];
  export type OutputTuple = [amount: bigint, newBalance: bigint];
  export interface OutputObject {
    amount: bigint;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntryPointWithdrawalEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionPerformedEvent {
  export type InputTuple = [
    caller: AddressLike,
    target: AddressLike,
    value: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    target: string,
    value: bigint,
    data: string
  ];
  export interface OutputObject {
    caller: string;
    target: string;
    value: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerChangedEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserOperationValidatedEvent {
  export type InputTuple = [
    userOpHash: BytesLike,
    signer: AddressLike,
    sessionId: BytesLike,
    value: BigNumberish
  ];
  export type OutputTuple = [
    userOpHash: string,
    signer: string,
    sessionId: string,
    value: bigint
  ];
  export interface OutputObject {
    userOpHash: string;
    signer: string;
    sessionId: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletInitializedEvent {
  export type InputTuple = [
    owner: AddressLike,
    sessionManager: AddressLike,
    entryPoint: AddressLike
  ];
  export type OutputTuple = [
    owner: string,
    sessionManager: string,
    entryPoint: string
  ];
  export interface OutputObject {
    owner: string;
    sessionManager: string;
    entryPoint: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhiteListUpdatedEvent {
  export type InputTuple = [party: AddressLike, status: boolean];
  export type OutputTuple = [party: string, status: boolean];
  export interface OutputObject {
    party: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentWallet extends BaseContract {
  connect(runner?: ContractRunner | null): AgentWallet;
  waitForDeployment(): Promise<this>;

  interface: AgentWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDeposit: TypedContractMethod<[], [void], "payable">;

  changeOwner: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  checkBalance: TypedContractMethod<[], [bigint], "view">;

  entryPoint: TypedContractMethod<[], [string], "view">;

  execute: TypedContractMethod<
    [target: AddressLike, value: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  executeBatch: TypedContractMethod<
    [targets: AddressLike[], values: BigNumberish[], data: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getDeposit: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [
      _owner: AddressLike,
      _sessionManager: AddressLike,
      _entryPoint: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  sessionManager: TypedContractMethod<[], [string], "view">;

  setWhiteListedParty: TypedContractMethod<
    [party: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setWhiteListedPartyBatch: TypedContractMethod<
    [parties: AddressLike[], statuses: boolean[]],
    [void],
    "nonpayable"
  >;

  validateUserOp: TypedContractMethod<
    [
      userOp: PackedUserOperationStruct,
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  whiteListedParties: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  withdrawDepositTo: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDeposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "changeOwner"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [target: AddressLike, value: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<
    [targets: AddressLike[], values: BigNumberish[], data: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _owner: AddressLike,
      _sessionManager: AddressLike,
      _entryPoint: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sessionManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setWhiteListedParty"
  ): TypedContractMethod<
    [party: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWhiteListedPartyBatch"
  ): TypedContractMethod<
    [parties: AddressLike[], statuses: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateUserOp"
  ): TypedContractMethod<
    [
      userOp: PackedUserOperationStruct,
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whiteListedParties"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawDepositTo"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchExecutionPerformed"
  ): TypedContractEvent<
    BatchExecutionPerformedEvent.InputTuple,
    BatchExecutionPerformedEvent.OutputTuple,
    BatchExecutionPerformedEvent.OutputObject
  >;
  getEvent(
    key: "EntryPointDepositAdded"
  ): TypedContractEvent<
    EntryPointDepositAddedEvent.InputTuple,
    EntryPointDepositAddedEvent.OutputTuple,
    EntryPointDepositAddedEvent.OutputObject
  >;
  getEvent(
    key: "EntryPointWithdrawal"
  ): TypedContractEvent<
    EntryPointWithdrawalEvent.InputTuple,
    EntryPointWithdrawalEvent.OutputTuple,
    EntryPointWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionPerformed"
  ): TypedContractEvent<
    ExecutionPerformedEvent.InputTuple,
    ExecutionPerformedEvent.OutputTuple,
    ExecutionPerformedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerChanged"
  ): TypedContractEvent<
    OwnerChangedEvent.InputTuple,
    OwnerChangedEvent.OutputTuple,
    OwnerChangedEvent.OutputObject
  >;
  getEvent(
    key: "UserOperationValidated"
  ): TypedContractEvent<
    UserOperationValidatedEvent.InputTuple,
    UserOperationValidatedEvent.OutputTuple,
    UserOperationValidatedEvent.OutputObject
  >;
  getEvent(
    key: "WalletInitialized"
  ): TypedContractEvent<
    WalletInitializedEvent.InputTuple,
    WalletInitializedEvent.OutputTuple,
    WalletInitializedEvent.OutputObject
  >;
  getEvent(
    key: "WhiteListUpdated"
  ): TypedContractEvent<
    WhiteListUpdatedEvent.InputTuple,
    WhiteListUpdatedEvent.OutputTuple,
    WhiteListUpdatedEvent.OutputObject
  >;

  filters: {
    "BatchExecutionPerformed(address,uint256,uint256)": TypedContractEvent<
      BatchExecutionPerformedEvent.InputTuple,
      BatchExecutionPerformedEvent.OutputTuple,
      BatchExecutionPerformedEvent.OutputObject
    >;
    BatchExecutionPerformed: TypedContractEvent<
      BatchExecutionPerformedEvent.InputTuple,
      BatchExecutionPerformedEvent.OutputTuple,
      BatchExecutionPerformedEvent.OutputObject
    >;

    "EntryPointDepositAdded(uint256,uint256)": TypedContractEvent<
      EntryPointDepositAddedEvent.InputTuple,
      EntryPointDepositAddedEvent.OutputTuple,
      EntryPointDepositAddedEvent.OutputObject
    >;
    EntryPointDepositAdded: TypedContractEvent<
      EntryPointDepositAddedEvent.InputTuple,
      EntryPointDepositAddedEvent.OutputTuple,
      EntryPointDepositAddedEvent.OutputObject
    >;

    "EntryPointWithdrawal(address,uint256)": TypedContractEvent<
      EntryPointWithdrawalEvent.InputTuple,
      EntryPointWithdrawalEvent.OutputTuple,
      EntryPointWithdrawalEvent.OutputObject
    >;
    EntryPointWithdrawal: TypedContractEvent<
      EntryPointWithdrawalEvent.InputTuple,
      EntryPointWithdrawalEvent.OutputTuple,
      EntryPointWithdrawalEvent.OutputObject
    >;

    "ExecutionPerformed(address,address,uint256,bytes)": TypedContractEvent<
      ExecutionPerformedEvent.InputTuple,
      ExecutionPerformedEvent.OutputTuple,
      ExecutionPerformedEvent.OutputObject
    >;
    ExecutionPerformed: TypedContractEvent<
      ExecutionPerformedEvent.InputTuple,
      ExecutionPerformedEvent.OutputTuple,
      ExecutionPerformedEvent.OutputObject
    >;

    "OwnerChanged(address,address)": TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;
    OwnerChanged: TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;

    "UserOperationValidated(bytes32,address,bytes32,uint256)": TypedContractEvent<
      UserOperationValidatedEvent.InputTuple,
      UserOperationValidatedEvent.OutputTuple,
      UserOperationValidatedEvent.OutputObject
    >;
    UserOperationValidated: TypedContractEvent<
      UserOperationValidatedEvent.InputTuple,
      UserOperationValidatedEvent.OutputTuple,
      UserOperationValidatedEvent.OutputObject
    >;

    "WalletInitialized(address,address,address)": TypedContractEvent<
      WalletInitializedEvent.InputTuple,
      WalletInitializedEvent.OutputTuple,
      WalletInitializedEvent.OutputObject
    >;
    WalletInitialized: TypedContractEvent<
      WalletInitializedEvent.InputTuple,
      WalletInitializedEvent.OutputTuple,
      WalletInitializedEvent.OutputObject
    >;

    "WhiteListUpdated(address,bool)": TypedContractEvent<
      WhiteListUpdatedEvent.InputTuple,
      WhiteListUpdatedEvent.OutputTuple,
      WhiteListUpdatedEvent.OutputObject
    >;
    WhiteListUpdated: TypedContractEvent<
      WhiteListUpdatedEvent.InputTuple,
      WhiteListUpdatedEvent.OutputTuple,
      WhiteListUpdatedEvent.OutputObject
    >;
  };
}
