/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ICredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeRoot"
      | "isNullifierUsed"
      | "markNullifierUsed"
      | "revokedSecretRoot"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activeRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isNullifierUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markNullifierUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokedSecretRoot",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "activeRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokedSecretRoot",
    data: BytesLike
  ): Result;
}

export interface ICredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ICredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: ICredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeRoot: TypedContractMethod<[], [string], "view">;

  isNullifierUsed: TypedContractMethod<
    [nullifier: BytesLike],
    [boolean],
    "view"
  >;

  markNullifierUsed: TypedContractMethod<
    [nullifier: BytesLike],
    [void],
    "nonpayable"
  >;

  revokedSecretRoot: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isNullifierUsed"
  ): TypedContractMethod<[nullifier: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markNullifierUsed"
  ): TypedContractMethod<[nullifier: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokedSecretRoot"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
