/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SessionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createLightweightSession"
      | "createSession"
      | "getLightSession"
      | "getWalletSessions"
      | "lightSessions"
      | "registry"
      | "revokeLightweightSession"
      | "revokeSession"
      | "sessions"
      | "validateLightweightSession"
      | "validateSession"
      | "verifier"
      | "walletSessions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DailyLimitsReset"
      | "LightSessionCreated"
      | "LightSessionRevoked"
      | "LightSessionUsed"
      | "SessionCreated"
      | "SessionRevoked"
      | "SessionUsed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createLightweightSession",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSession",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getLightSession",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWalletSessions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lightSessions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeLightweightSession",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeSession",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "sessions", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "validateLightweightSession",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateSession",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "walletSessions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createLightweightSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLightSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWalletSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lightSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeLightweightSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sessions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateLightweightSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "walletSessions",
    data: BytesLike
  ): Result;
}

export namespace DailyLimitsResetEvent {
  export type InputTuple = [sessionId: BytesLike, newDay: BigNumberish];
  export type OutputTuple = [sessionId: string, newDay: bigint];
  export interface OutputObject {
    sessionId: string;
    newDay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LightSessionCreatedEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    sessionKey: AddressLike,
    dailySpendLimit: BigNumberish,
    dailyTxLimit: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: string,
    sessionKey: string,
    dailySpendLimit: bigint,
    dailyTxLimit: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    sessionId: string;
    sessionKey: string;
    dailySpendLimit: bigint;
    dailyTxLimit: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LightSessionRevokedEvent {
  export type InputTuple = [sessionId: BytesLike];
  export type OutputTuple = [sessionId: string];
  export interface OutputObject {
    sessionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LightSessionUsedEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    value: BigNumberish,
    newDailySpend: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: string,
    value: bigint,
    newDailySpend: bigint
  ];
  export interface OutputObject {
    sessionId: string;
    value: bigint;
    newDailySpend: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionCreatedEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    sessionKey: AddressLike,
    expiry: BigNumberish,
    maxValue: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: string,
    sessionKey: string,
    expiry: bigint,
    maxValue: bigint
  ];
  export interface OutputObject {
    sessionId: string;
    sessionKey: string;
    expiry: bigint;
    maxValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionRevokedEvent {
  export type InputTuple = [sessionId: BytesLike];
  export type OutputTuple = [sessionId: string];
  export interface OutputObject {
    sessionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionUsedEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    value: BigNumberish,
    totalUsed: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: string,
    value: bigint,
    totalUsed: bigint
  ];
  export interface OutputObject {
    sessionId: string;
    value: bigint;
    totalUsed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SessionManager extends BaseContract {
  connect(runner?: ContractRunner | null): SessionManager;
  waitForDeployment(): Promise<this>;

  interface: SessionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createLightweightSession: TypedContractMethod<
    [
      sessionId: BytesLike,
      sessionKey: AddressLike,
      dailySpendLimit: BigNumberish,
      dailyTxLimit: BigNumberish,
      expiry: BigNumberish,
      ownerSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createSession: TypedContractMethod<
    [
      sessionId: BytesLike,
      sessionKey: AddressLike,
      maxValue: BigNumberish,
      expiry: BigNumberish,
      nullifier: BytesLike,
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      publicSignals: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ],
    [void],
    "nonpayable"
  >;

  getLightSession: TypedContractMethod<
    [sessionId: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        sessionKey: string;
        dailySpendLimit: bigint;
        dailyTxLimit: bigint;
        dailySpendUsed: bigint;
        dailyTxUsed: bigint;
        expiry: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getWalletSessions: TypedContractMethod<
    [wallet: AddressLike],
    [string[]],
    "view"
  >;

  lightSessions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        sessionKey: string;
        dailySpendLimit: bigint;
        dailyTxLimit: bigint;
        dailySpendUsed: bigint;
        dailyTxUsed: bigint;
        lastResetDay: bigint;
        expiry: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  revokeLightweightSession: TypedContractMethod<
    [sessionId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeSession: TypedContractMethod<
    [sessionId: BytesLike],
    [void],
    "nonpayable"
  >;

  sessions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        sessionKey: string;
        valueUsed: bigint;
        maxValue: bigint;
        expiry: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  validateLightweightSession: TypedContractMethod<
    [sessionId: BytesLike, signer: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  validateSession: TypedContractMethod<
    [sessionId: BytesLike, signer: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  walletSessions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createLightweightSession"
  ): TypedContractMethod<
    [
      sessionId: BytesLike,
      sessionKey: AddressLike,
      dailySpendLimit: BigNumberish,
      dailyTxLimit: BigNumberish,
      expiry: BigNumberish,
      ownerSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSession"
  ): TypedContractMethod<
    [
      sessionId: BytesLike,
      sessionKey: AddressLike,
      maxValue: BigNumberish,
      expiry: BigNumberish,
      nullifier: BytesLike,
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      publicSignals: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLightSession"
  ): TypedContractMethod<
    [sessionId: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        sessionKey: string;
        dailySpendLimit: bigint;
        dailyTxLimit: bigint;
        dailySpendUsed: bigint;
        dailyTxUsed: bigint;
        expiry: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWalletSessions"
  ): TypedContractMethod<[wallet: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "lightSessions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        sessionKey: string;
        dailySpendLimit: bigint;
        dailyTxLimit: bigint;
        dailySpendUsed: bigint;
        dailyTxUsed: bigint;
        lastResetDay: bigint;
        expiry: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeLightweightSession"
  ): TypedContractMethod<[sessionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeSession"
  ): TypedContractMethod<[sessionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sessions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        sessionKey: string;
        valueUsed: bigint;
        maxValue: bigint;
        expiry: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateLightweightSession"
  ): TypedContractMethod<
    [sessionId: BytesLike, signer: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateSession"
  ): TypedContractMethod<
    [sessionId: BytesLike, signer: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "walletSessions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "DailyLimitsReset"
  ): TypedContractEvent<
    DailyLimitsResetEvent.InputTuple,
    DailyLimitsResetEvent.OutputTuple,
    DailyLimitsResetEvent.OutputObject
  >;
  getEvent(
    key: "LightSessionCreated"
  ): TypedContractEvent<
    LightSessionCreatedEvent.InputTuple,
    LightSessionCreatedEvent.OutputTuple,
    LightSessionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LightSessionRevoked"
  ): TypedContractEvent<
    LightSessionRevokedEvent.InputTuple,
    LightSessionRevokedEvent.OutputTuple,
    LightSessionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "LightSessionUsed"
  ): TypedContractEvent<
    LightSessionUsedEvent.InputTuple,
    LightSessionUsedEvent.OutputTuple,
    LightSessionUsedEvent.OutputObject
  >;
  getEvent(
    key: "SessionCreated"
  ): TypedContractEvent<
    SessionCreatedEvent.InputTuple,
    SessionCreatedEvent.OutputTuple,
    SessionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SessionRevoked"
  ): TypedContractEvent<
    SessionRevokedEvent.InputTuple,
    SessionRevokedEvent.OutputTuple,
    SessionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SessionUsed"
  ): TypedContractEvent<
    SessionUsedEvent.InputTuple,
    SessionUsedEvent.OutputTuple,
    SessionUsedEvent.OutputObject
  >;

  filters: {
    "DailyLimitsReset(bytes32,uint64)": TypedContractEvent<
      DailyLimitsResetEvent.InputTuple,
      DailyLimitsResetEvent.OutputTuple,
      DailyLimitsResetEvent.OutputObject
    >;
    DailyLimitsReset: TypedContractEvent<
      DailyLimitsResetEvent.InputTuple,
      DailyLimitsResetEvent.OutputTuple,
      DailyLimitsResetEvent.OutputObject
    >;

    "LightSessionCreated(bytes32,address,uint256,uint256,uint64)": TypedContractEvent<
      LightSessionCreatedEvent.InputTuple,
      LightSessionCreatedEvent.OutputTuple,
      LightSessionCreatedEvent.OutputObject
    >;
    LightSessionCreated: TypedContractEvent<
      LightSessionCreatedEvent.InputTuple,
      LightSessionCreatedEvent.OutputTuple,
      LightSessionCreatedEvent.OutputObject
    >;

    "LightSessionRevoked(bytes32)": TypedContractEvent<
      LightSessionRevokedEvent.InputTuple,
      LightSessionRevokedEvent.OutputTuple,
      LightSessionRevokedEvent.OutputObject
    >;
    LightSessionRevoked: TypedContractEvent<
      LightSessionRevokedEvent.InputTuple,
      LightSessionRevokedEvent.OutputTuple,
      LightSessionRevokedEvent.OutputObject
    >;

    "LightSessionUsed(bytes32,uint256,uint256)": TypedContractEvent<
      LightSessionUsedEvent.InputTuple,
      LightSessionUsedEvent.OutputTuple,
      LightSessionUsedEvent.OutputObject
    >;
    LightSessionUsed: TypedContractEvent<
      LightSessionUsedEvent.InputTuple,
      LightSessionUsedEvent.OutputTuple,
      LightSessionUsedEvent.OutputObject
    >;

    "SessionCreated(bytes32,address,uint64,uint128)": TypedContractEvent<
      SessionCreatedEvent.InputTuple,
      SessionCreatedEvent.OutputTuple,
      SessionCreatedEvent.OutputObject
    >;
    SessionCreated: TypedContractEvent<
      SessionCreatedEvent.InputTuple,
      SessionCreatedEvent.OutputTuple,
      SessionCreatedEvent.OutputObject
    >;

    "SessionRevoked(bytes32)": TypedContractEvent<
      SessionRevokedEvent.InputTuple,
      SessionRevokedEvent.OutputTuple,
      SessionRevokedEvent.OutputObject
    >;
    SessionRevoked: TypedContractEvent<
      SessionRevokedEvent.InputTuple,
      SessionRevokedEvent.OutputTuple,
      SessionRevokedEvent.OutputObject
    >;

    "SessionUsed(bytes32,uint256,uint256)": TypedContractEvent<
      SessionUsedEvent.InputTuple,
      SessionUsedEvent.OutputTuple,
      SessionUsedEvent.OutputObject
    >;
    SessionUsed: TypedContractEvent<
      SessionUsedEvent.InputTuple,
      SessionUsedEvent.OutputTuple,
      SessionUsedEvent.OutputObject
    >;
  };
}
