/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISessionManager,
  ISessionManagerInterface,
} from "../../AgentWallet.sol/ISessionManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "sessionId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "signer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "validateLightweightSession",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "sessionId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "signer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "validateSession",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISessionManager__factory {
  static readonly abi = _abi;
  static createInterface(): ISessionManagerInterface {
    return new Interface(_abi) as ISessionManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISessionManager {
    return new Contract(address, _abi, runner) as unknown as ISessionManager;
  }
}
