/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentWallet,
  IAgentWalletInterface,
} from "../../AgentWalletFactory.sol/IAgentWallet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "sessionManager",
        type: "address",
      },
      {
        internalType: "address",
        name: "entryPoint",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentWallet__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentWalletInterface {
    return new Interface(_abi) as IAgentWalletInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentWallet {
    return new Contract(address, _abi, runner) as unknown as IAgentWallet;
  }
}
