/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentWallet,
  IAgentWalletInterface,
} from "../../SessionManager.sol/IAgentWallet";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAgentWallet__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentWalletInterface {
    return new Interface(_abi) as IAgentWalletInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentWallet {
    return new Contract(address, _abi, runner) as unknown as IAgentWallet;
  }
}
