/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICredentialRegistry,
  ICredentialRegistryInterface,
} from "../../SessionManager.sol/ICredentialRegistry";

const _abi = [
  {
    inputs: [],
    name: "activeRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "nullifier",
        type: "bytes32",
      },
    ],
    name: "isNullifierUsed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "nullifier",
        type: "bytes32",
      },
    ],
    name: "markNullifierUsed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "revokedSecretRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICredentialRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ICredentialRegistryInterface {
    return new Interface(_abi) as ICredentialRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICredentialRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICredentialRegistry;
  }
}
