/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeRoot"
      | "addIssuer"
      | "isNullifierUsed"
      | "issuers"
      | "markNullifierUsed"
      | "owner"
      | "removeIssuer"
      | "revokedSecretRoot"
      | "sessionManagers"
      | "setSessionManager"
      | "updateActiveRoot"
      | "updateRevokedSecretRoot"
      | "usedNullifiers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActiveRootUpdated"
      | "CredentialIssued"
      | "CredentialRevoked"
      | "RevokedSecretRootUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isNullifierUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markNullifierUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokedSecretRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sessionManagers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSessionManager",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateActiveRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRevokedSecretRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedNullifiers",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "activeRoot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issuers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokedSecretRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sessionManagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSessionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateActiveRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRevokedSecretRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedNullifiers",
    data: BytesLike
  ): Result;
}

export namespace ActiveRootUpdatedEvent {
  export type InputTuple = [newRoot: BytesLike];
  export type OutputTuple = [newRoot: string];
  export interface OutputObject {
    newRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    issuer: AddressLike,
    agentId: BigNumberish,
    commitment: BytesLike,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    issuer: string,
    agentId: bigint,
    commitment: string,
    expiry: bigint
  ];
  export interface OutputObject {
    issuer: string;
    agentId: bigint;
    commitment: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [issuer: AddressLike, secretHash: BytesLike];
  export type OutputTuple = [issuer: string, secretHash: string];
  export interface OutputObject {
    issuer: string;
    secretHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevokedSecretRootUpdatedEvent {
  export type InputTuple = [newRoot: BytesLike];
  export type OutputTuple = [newRoot: string];
  export interface OutputObject {
    newRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: CredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeRoot: TypedContractMethod<[], [string], "view">;

  addIssuer: TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;

  isNullifierUsed: TypedContractMethod<
    [nullifier: BytesLike],
    [boolean],
    "view"
  >;

  issuers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  markNullifierUsed: TypedContractMethod<
    [nullifier: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  revokedSecretRoot: TypedContractMethod<[], [string], "view">;

  sessionManagers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setSessionManager: TypedContractMethod<
    [sessionManager: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  updateActiveRoot: TypedContractMethod<
    [newRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  updateRevokedSecretRoot: TypedContractMethod<
    [newRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  usedNullifiers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isNullifierUsed"
  ): TypedContractMethod<[nullifier: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markNullifierUsed"
  ): TypedContractMethod<[nullifier: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokedSecretRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sessionManagers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setSessionManager"
  ): TypedContractMethod<
    [sessionManager: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateActiveRoot"
  ): TypedContractMethod<[newRoot: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRevokedSecretRoot"
  ): TypedContractMethod<[newRoot: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedNullifiers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "ActiveRootUpdated"
  ): TypedContractEvent<
    ActiveRootUpdatedEvent.InputTuple,
    ActiveRootUpdatedEvent.OutputTuple,
    ActiveRootUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RevokedSecretRootUpdated"
  ): TypedContractEvent<
    RevokedSecretRootUpdatedEvent.InputTuple,
    RevokedSecretRootUpdatedEvent.OutputTuple,
    RevokedSecretRootUpdatedEvent.OutputObject
  >;

  filters: {
    "ActiveRootUpdated(bytes32)": TypedContractEvent<
      ActiveRootUpdatedEvent.InputTuple,
      ActiveRootUpdatedEvent.OutputTuple,
      ActiveRootUpdatedEvent.OutputObject
    >;
    ActiveRootUpdated: TypedContractEvent<
      ActiveRootUpdatedEvent.InputTuple,
      ActiveRootUpdatedEvent.OutputTuple,
      ActiveRootUpdatedEvent.OutputObject
    >;

    "CredentialIssued(address,uint64,bytes32,uint64)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "CredentialRevoked(address,bytes32)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "RevokedSecretRootUpdated(bytes32)": TypedContractEvent<
      RevokedSecretRootUpdatedEvent.InputTuple,
      RevokedSecretRootUpdatedEvent.OutputTuple,
      RevokedSecretRootUpdatedEvent.OutputObject
    >;
    RevokedSecretRootUpdated: TypedContractEvent<
      RevokedSecretRootUpdatedEvent.InputTuple,
      RevokedSecretRootUpdatedEvent.OutputTuple,
      RevokedSecretRootUpdatedEvent.OutputObject
    >;
  };
}
